name: Check the gold price

on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:

env:
  PASS: ${{ secrets.PASS }}
  APP_KEY: ${{ secrets.APP_KEY }}
  SIGN: ${{ secrets.SIGN }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependency
        run: npm install

      - name: Run
        run: node index.js
