name: Check the gold price

# - cron: "20 0 * * *"  # 每天 00:20 自动执行

on:
  schedule:
    - cron: "30 23 * * *" # 每天 23:30 自动执行
  workflow_dispatch: # 允许手动触发

env:
  PASS: ${{ secrets.PASS }}
  APP_KEY: ${{ secrets.APP_KEY }}
  SIGN: ${{ secrets.SIGN }}
  SEND_MAIL: ${{ secrets.SEND_MAIL }}
  MAIL: ${{ secrets.MAIL }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependency
        run: npm install

      - name: Run
        run: node index.js
